name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [closed]

jobs:
  build-and-deploy:
   
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Build and push Nginx (frontend) image
      - name: Build and push Nginx image
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ secrets.BACKEND_URL }} \
            --build-arg VITE_WS_URL=${{ secrets.WEB_SOCKET_URL }} \
            -f ./Frontend/Dockerfile.front \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx-img:latest ./
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx-img:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx-img:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx-img:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-nginx-img:${{ github.sha }}

      # Build and push Backend image
      - name: Build and push Backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-backend-img:latest -f ./Backend/Dockerfile.backend ./Backend
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/my-backend-img:latest ${{ secrets.DOCKERHUB_USERNAME }}/my-backend-img:${{ github.sha }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-backend-img:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-backend-img:${{ github.sha }}

      # Deploy to server
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd /home/azureuser/app
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
